//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC5Course.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Client
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Client()
        {
            this.Order = new HashSet<Order>();
        }

        public int ClientId { get; set; }
        [DisplayName("名")]
        [Required]
        [StringLength(10,ErrorMessage ="{0} Firstname Cannot input over {1} words.")]
        public string FirstName { get; set; }
        [DisplayName("中間名")]
        [Required]
        [StringLength(10,ErrorMessage ="{0} Middlename Cannot input over {1} words.")]
        public string MiddleName { get; set; }
        [DisplayName("姓")]
        [Required]
        [StringLength(10,ErrorMessage ="{0} Lastname Cannot input over {1} words.")]
        public string LastName { get; set; }
        [DisplayName("性別")]
        [Required]
        [RegularExpression("[MF]",ErrorMessage ="{0}只能輸入M或F!")]
        public string Gender { get; set; }
        [DisplayName("生日")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString ="{0:yyyy/MM/dd}",ApplyFormatInEditMode =true)]
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        [DisplayName("信用評比")]
        [Range(0,9,ErrorMessage ="{0} needs between 0-9!")]
        public Nullable<double> CreditRating { get; set; }
        [DisplayName("X密碼")]
        public string XCode { get; set; }

        public Nullable<int> OccupationId { get; set; }
        [DisplayName("手機號碼")]
        //[DisplayFormat(DataFormatString = "{0:(###)###-####}")]
       // [RegularExpression("^\(? (\d{2})\)?[\s\-]?(\d{4})\-?(\d{4})$")]
        public string TelephoneNumber { get; set; }
        public string Street1 { get; set; }
        public string Street2 { get; set; }
        public string City { get; set; }
        public string ZipCode { get; set; }
        public Nullable<double> Longitude { get; set; }
        public Nullable<double> Latitude { get; set; }
        public string Notes { get; set; }
    
        public virtual Occupation Occupation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Order { get; set; }
    }
}
